import type { Metadata } from "next";
import '@src/app/globals.scss'
import {Raleway} from 'next/font/google'


const raleway = Raleway({subsets: ['latin'], weight: ["400", "700"]})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${raleway.className} text-slate-900 bg-slate-50`}
      >
        {children}
      </body>
    </html>
  );
}
