import type { Metadata } from "next";
import "@src/app/globals.scss";
import { Roboto } from "next/font/google";

const roboto = Roboto({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "Ostapuk - Fullstack Developer | Portfolio",
  description:
    "Explore Ostapuk's portfolio showcasing web development projects, skills, and experience. A Fullstack Developer focused on creating high-quality web applications, with expertise in JavaScript, React, Node.js, Next.js, and more.",
  keywords: [
    "Ostapuk",
    "Ostapuk Olexandr Mykolayovych",
    "Ostapuk Sasha",
    "Ostapuk Olexandr",
    "Olexandr Ostapuk",
    "Ostapuk Developer",
    "Ostapuk Fullstack Developer",
    "Ostapuk Olexandr Fullstack",
    "Ostapuk Olexandr Web Developer",
    "Ostapuk Web Developer",
    "Ostapuk Freelance Developer",
    "Ostapuk Frontend Developer",
    "Ostapuk Backend Developer",
    "Ostapuk Fullstack Web Developer",
    "Fullstack Developer",
    "Web Developer",
    "Freelance Developer",
    "Frontend Developer",
    "Backend Developer",
    "Fullstack Web Developer",
    "Freelance Fullstack Developer",
    "Senior Web Developer",
    "Junior Web Developer",
    "Lead Developer",
    "Freelance Fullstack Web Developer",
    "Frontend Web Developer",
    "Backend Web Developer",

    // Technologies
    "JavaScript",
    "React",
    "Node.js",
    "Next.js",
    "Frontend Development",
    "Backend Development",
    "Fullstack Development",
    "JavaScript Developer",
    "React Developer",
    "Node.js Developer",
    "Next.js Developer",
    "Frontend JavaScript Developer",
    "Backend JavaScript Developer",
    "Fullstack JavaScript Developer",
    "JavaScript Web Developer",
    "React.js",
    "Vue.js",
    "Angular",
    "SASS",
    "GraphQL",
    "Express.js",
    "NestJS",
    "TypeScript",
    "Jest",
    "Redux",
    "MongoDB",
    "SQL",
    "MySQL",
    "PostgreSQL",
    "Web Development Frameworks",
    "Microservices Architecture",
    "Web Development Tools",
    "DevOps Developer",

    // Web Development Services
    "Web Development",
    "Freelance Web Development",
    "Web Design",
    "Web Applications",
    "Web Development Projects",
    "Custom Web Development",
    "Responsive Web Design",
    "Mobile Web Development",
    "Website Development",
    "E-commerce Development",
    "Fullstack Web Development Services",
    "Freelance Fullstack Web Development",
    "Web Application Development",
    "Fullstack Web Development Projects",
    "Freelance Web Application Development",
    "Website Design and Development",
    "Web Development Consulting",
    "Web Development Solutions",
    "UI/UX Design",
    "Progressive Web App Development",
    "Single Page Application Development",
    "Fullstack Web Development for Startups",

    // Ukrainian Keywords for Local SEO
    "Остапук",
    "Остапук Олександр Миколайович",
    "Остапук Саша",
    "Остапук Олександр",
    "Олександр Остапук",
    "Остапук Розробник",
    "Остапук Фуллстак Розробник",
    "Остапук Олександр Фуллстак",
    "Остапук Олександр Веб Розробник",
    "Фулстек Розробник",
    "Веб-Розробник",
    "Фріланс Розробник",
    "Фронтенд Розробник",
    "Бекенд Розробник",
    "JavaScript Розробник",
    "React Розробник",
    "Node.js Розробник",
    "Next.js Розробник",
    "Розробка Веб-Додатків",
    "Фронтенд Розробка",
    "Бекенд Розробка",
    "Портфоліо Розробника",
    "Фріланс Веб-Розробка",
    "Веб-Додатки",
    "Веб-Дизайн",
    "Проекти Веб-Розробки",
    "Фулстек Веб-Розробка",
    "Фронтенд Веб-Розробка",
    "Бекенд Веб-Розробка",
    "Веб-Сайти Для Бізнесу",
    "Дизайн Та Розробка Веб-Сайтів",
    "Інтернет-Магазини",
    "Розробка Мобільних Додатків",
    "Віддалена Розробка Веб-Сайтів",
    "Фріланс Веб-Розробка Послуги",
    "Веб-Розробка Для Стартапів",

    // Russian Keywords for Local SEO
    "Остапук",
    "Остапук Олександр Миколайович",
    "Остапук Саша",
    "Остапук Олександр",
    "Олександр Остапук",
    "Остапук Разработчик",
    "Остапук Фуллстак Разработчик",
    "Остапук Олександр Фуллстак",
    "Остапук Олександр Веб Разработчик",
    "Фуллстек Разработчик",
    "Веб-Разработчик",
    "Фриланс Разработчик",
    "Фронтенд Разработчик",
    "Бекенд Разработчик",
    "JavaScript Разработчик",
    "React Разработчик",
    "Node.js Разработчик",
    "Next.js Разработчик",
    "Разработка Веб-Приложений",
    "Фронтенд Разработка",
    "Бекенд Разработка",
    "Портфолио Разработчика",
    "Фриланс Веб-Разработка",
    "Веб-Приложения",
    "Веб-Дизайн",
    "Проекты Веб-Разработки",
    "Фуллстек Веб-Разработка",
    "Фронтенд Веб-Разработка",
    "Бекенд Веб-Разработка",
    "Сайты Для Бизнеса",
    "Разработка Сайтов",
    "Дизайн И Разработка Сайтов",
    "Интернет-Магазины",
    "Разработка Мобильных Приложений",
    "Удаленная Веб-Разработка",
    "Фриланс Веб-Разработка Услуги",
    "Веб-Разработка Для Стартапов",
    "Дизайн И Разработка Интерфейсов",
    "Система Управления Контентом (CMS)",
    "Персональные Сайты Для Бизнеса",
    "Поддержка И Обслуживание Сайтов",
    "Создание Сайтов На Заказ",

    // Additional Keywords
    "JavaScript freelance developer",
    "fullstack web development services",
    "freelance developer for startups",
    "web development portfolio",
    "freelance web design",
    "JavaScript freelance web developer",
    "web development contract",
    "next.js freelance developer",
    "react freelance developer",
    "hire a freelance web developer",
    "web application expert",
    "custom web development services",
    "hire freelance fullstack developer",
    "web development specialist",
    "best freelance developer",
  ],

  authors: [{ name: "Ostapuk Oleksandr" }],
  robots: "index, follow",
  icons: "favicon.ico",
  openGraph: {
    type: "website",
    url: "https://ostapuk.tech",
    title: "Ostapuk - Fullstack Developer | Portfolio",
    description:
      "Explore Ostapuk's portfolio showcasing web development projects, skills, and experience. A Fullstack Developer focused on creating high-quality web applications, specializing in JavaScript, React, Node.js, and more.",
    images: [
      {
        url: "https://res.cloudinary.com/dzivbyc4z/image/upload/v1728663650/avatar_wfztoa.jpg",
        width: 1200,
        height: 630,
        alt: "Ostapuk Oleksandr - Остапук Олександр Portfolio",
      },
    ],
  },
  other: {
    freelancehunt: "04a600f4ed399fa",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.className} bg-slate-50`}>{children}</body>
    </html>
  );
}
